# Generated by Django 5.1.7 on 2025-03-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(default='NewUser', max_length=50),
        ),
    ]
